### DISCUSSION TITLE
Integrating Storybook interaction tests into test coverage and CI

### DISCUSSION THREAD

**Discussion by cgat** [storybookjs/storybook#16841] [Help] [answered]
Hi,

I'm super excited to use the new interactions addon. One part that I'm confused about this is that we are effectively writing tests (granted this doesn't always have to be the case) for our components, but now these tests won't be run along side our other jest tests. Is there a recommended way to run the play script in the context of jest? One thought would be to use the puppeteer addon to run the interactions, which might make sense if we want to capture the screenshots after an interaction has occurred. In that regard, are they any elegant ways to hook into the interactions api and imageStorySnaps?

Thanks,

Chris

**Comment by shilman** [comment, marked as answer]
We are planning a test runner to be released in 6.5 that will run in CI

**Comment by acherkashin** [comment]
Hi guys,

First of all, thank you for your great job and making Storybook better and better with every release! 

I'm excited about the new interaction tests feature. These tests primarily will be run on CI, in the same way as jest tests. Unfortunately, I didn't find good documentation on how to run them in CI. 

I've researched a bit and what I understood is It is required to publish storybook somewhere (like chromatic) to be able to run interactive tests. We can see it by following screenshot that was published in [Interaction Tests with Storybook](https://storybook.js.org/blog/interaction-testing-with-storybook/).

![image](https://user-images.githubusercontent.com/9947582/161616671-cd83eb1a-7716-419a-a777-e98614658780.png)

Is it possible to run storybook interaction tests without publishing storybook? I would like it to work in the same way as jest tests with single command `yarn run test`.

**Reply by cgat** [reply]
See above. Slated for 6.5 release, which is in alpha

**Reply by shilman** [reply]
There's CI instructions in the README and we're in the process of adding them to the official docs. 

Unfortunately you can't test in a single command, but you can create a single npm script to test

https://www.npmjs.com/package/@storybook/test-runner#running-in-ci

**Reply by acherkashin** [reply]
@shilman Thank you, that is exactly what I looked for. It works.

https://gitlab.com/cherkalexander/test-examples/-/jobs/2291496157

**Comment by stuthib** [comment]
Hey all, the above discussion was super helpful for me to get started with setting up CI actions on storybook tests. I am trying to run the coverage report on CI, but it fails with this error - 
```
[Test runner] An error occurred when evaluating code coverage:
[TEST]       The code in this story is not instrumented, which means the coverage setup is likely not correct.
[TEST]       More info: https://github.com/storybookjs/test-runner#setting-up-code-coverage
```
This is my CI set-up
```
name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: npm lint
        run: npm run lint
      - name: Test coverage
        run: npm run test-coverage
      - name: Build Storybook
        run: npm run build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npx test-storybook --coverage"
      - name: Total coverage
        uses: paambaati/codeclimate-action@v3.1.1
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ID }}
        with:
          coverageCommand: npm run coverage:convert
```

It works fine when I run `npx test-storybook --coverage` locally though.

Would appreciate any insights on this.
