### DISCUSSION TITLE
Storybook loading locally but not on GH-Pages, failed to fetch!

### DISCUSSION THREAD

**Discussion by jay-cascade** [storybookjs/storybook#20588] [Help]
Hi,

I obviously have something not quite configured correctly! When I build storybook and serve it locally with 'http-server' it works just fine. But when I deploy to gh-pages with github actions, I get the following error: 'Failed to fetch dynamically imported module'

You can see here: [https://hydradatasystems.github.io/hds-components/](https://hydradatasystems.github.io/hds-components/)

Any help on getting this issue resolved would be greatly appreciated, thanks.

Some files:

package.json

```
{
  "name": "@hydradatasystems/hds-components",
  "version": "0.0.1",
  "engines": {
    "node": ">=18.12.0",
    "npm": ">=8.19.2"
  },
  "main": "dist/index.umd.js",
  "module": "dist/index.es.js",
  "types": "dist/index.d.ts",
  "homepage": "https://hydradatasystems.github.io/hds-components",
  "exports": {
    ".": {
      "require": "./dist/index.umd.js",
      "import": "./dist/index.es.js"
    },
    "./dist/style.css": "./dist/style.css"
  },
  "sideEffects": false,
  "files": [
    "dist"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/HydraDataSystems/hds-components.git"
  },
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/hydradatasystems"
  },
  "scripts": {
    "dev": "vite",
    "build": "rm -rf dist && run-p build:*",
    "build:scripts": "vite build",
    "build:types": "tsc --emitDeclarationOnly && tsc-alias",
    "preview": "vite preview",
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build",
    "test": "jest"
  },
  "peerDependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@storybook/addon-actions": "^7.0.0-beta.21",
    "@storybook/addon-essentials": "^7.0.0-beta.21",
    "@storybook/addon-interactions": "^7.0.0-beta.21",
    "@storybook/addon-links": "^7.0.0-beta.21",
    "@storybook/react": "^7.0.0-beta.21",
    "@storybook/react-vite": "^7.0.0-beta.21",
    "@storybook/testing-library": "^0.0.14-next.1",
    "@storybook/testing-react": "^2.0.0-next.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@types/jest": "^29.1.2",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "autoprefixer": "^10.4.12",
    "babel-loader": "^8.2.5",
    "gh-pages": "^4.0.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^29.2.0",
    "jest-environment-jsdom": "^29.2.0",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.17",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "storybook": "^7.0.0-beta.21",
    "tailwindcss": "^3.1.8",
    "ts-jest": "^29.0.3",
    "tsc-alias": "^1.7.0",
    "typed-css-modules": "^0.7.2",
    "typescript": "^4.6.4",
    "vite-plugin-dts": "^1.7.1",
    "vite-plugin-ts": "^1.3.2-1",
    "vite-tsconfig-paths": "^4.0.3"
  },
  "dependencies": {
    "@vitejs/plugin-react": "^3.0.1",
    "react-icons": "^4.4.0",
    "vite": "^4.0.4"
  }
}
```

.github/workflows/storybook.yml

```
name: Storybook
on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm ci
          GH_PAGES=true npm run build-storybook
          npm test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: storybook-static
```

.storybook/main.cjs

```
module.exports = {
  "stories": ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  "addons": ["@storybook/addon-links", "@storybook/addon-essentials", "@storybook/addon-interactions"],
  "framework": {
    name: "@storybook/react-vite",
    options: {}
  },
  "features": {
    "storyStoreV7": true
  },
  viteFinal: async config => {
    if (process.env.GH_PAGES) {
      config.base = "https://hydradatasystems.github.io/hds-components/";
    }
    return config;
  },
  docs: {
    autodocs: true
  }
};

```
