### DISCUSSION TITLE
How to hide toolbar in Docs

### DISCUSSION THREAD

**Discussion by kwickramasekara** [storybookjs/storybook#20620] [Help]
I would like to hide the toolbar only within docs pages. I tried the configuration [shown here](https://storybook.js.org/docs/7.0/web-components/configure/features-and-behavior) but this hides toolbar items for both stories and docs pages. And I still see globals in the docs toolbar as seen below. Any possibility to configure it to hide toolbar completely on docs pages?

Note: I am on the latest beta version: `7.0.0-beta.25`

![image](https://user-images.githubusercontent.com/6528584/212399660-53879f45-e328-4118-b97d-0979dc4a05e8.png)

**Comment by TriveniBrijesh** [comment]
I'm still facing same issue any one resolved?

**Comment by kerryj89** [comment]
It seems like a regression, I tried all manners of the option and even looked at what others have done at [https://sourcegraph.com/search?q=context%3Aglobal+showToolbar+file%3Amdx&patternType=standard&sm=1&groupBy=repo](url)

I believe @shilman opened an issue for this at https://github.com/storybookjs/storybook/issues/21427

I noticed an extra element between docs and canvas view (well, doc being my .mdx, idk for other formats) and hooked onto that difference to hide the toolbar via css.

**Storybook v7**
```html
// .storybook/manager-head.html

<!DOCTYPE html>
<head>
  <style>
    [role='main']:nth-child(5) div:has(+ [offset]) {
      display: none;
    }

    [role='main']:nth-child(5) [offset] {
      top: 0;
      height: 100%;
    }
  </style>
</head>
```

**Storybook v8**
Requires using `:has()` due to changes in markup and attributes

```css
/* :nth-child(4) is the  "Addons" pane at the bottom of individual Stories view */
[id='root'] > div:not(:has(> :nth-child(4))) [data-test-id='sb-preview-toolbar'] {
    display: none;
}
```

Here's to hoping the bug gets fixed sooner.
