### DISCUSSION TITLE
How to deploy to GitHub Pages?

### DISCUSSION THREAD

**Discussion by denchen** [storybookjs/storybook#20932] [Help] [answered]
I saw that `storybook-deployer` has been EOL'd. So I'm wondering with Storybook v7 and onwards, what's the path to deploy to ghpages in my CI pipeline?

**Comment by AmiramAbergel** [comment]
using the github-pages-deploy-action GitHub Action:

1. Create a new GitHub Actions workflow in your repository by creating a .github/workflows/deploy.yml file with the following contents:

```
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and deploy Storybook
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./storybook-static
```

* Note: Replace ./storybook-static with the path to your built Storybook directory.

2. In your CI pipeline, build your Storybook as you normally would.
3. Push your changes to the main branch of your repository, which will trigger the GitHub Actions workflow to deploy your Storybook to GitHub Pages.

With this approach, you don't have to worry about setting up any additional tools or dependencies, as GitHub Action takes care of the deployment for you.

**Reply by booc0mtaco** [reply]
If using this, it pays to read [the docs](https://github.com/peaceiris/actions-gh-pages). You will need to configure the token, and trigger a `storybook build` to make sure there is content TO publish.

**Comment by literalpie** [comment]
The docs still mention storybook-deployer [here](https://storybook.js.org/docs/7.0/react/sharing/publish-storybook). It would be nice if alternatives were documented there and in the now-archived storybook-deployer repo's readme

**Comment by mderazon** [comment]
With the new [Github Actions for Github Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow):
```yml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build-storybook
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./storybook-static"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

**Comment by mickmcgrath13** [comment, marked as answer]
We're on a mission to make things like this easier!

Here's our take on a simplified Storybook to GitHub Pages action:
https://github.com/marketplace/actions/deploy-storybook-to-github-pages

It does a build (command is customizable), and a publish to GitHub pages with the Actions based pages deployment.  You can also customize the output directory.

usage:
```yaml
name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
      with:
        path: dist/storybook
```
> Build command is customizable. default is `npm run build-storybook`

([corresponding blog post](https://www.bitovi.com/blog/deploy-storybook-to-github-pages-with-github-actions) if you're into that sort of thing ;) )


> Be sure to [set up your project](https://github.com/marketplace/actions/deploy-storybook-to-github-pages#set-up-your-project-for-actions-deployed-pages) for action based pages deployments


We are actively maintaining this project :)
