### DISCUSSION TITLE
StaticDirs not working as expected with Angular 17 and nx

### DISCUSSION THREAD

**Discussion by janphi001** [storybookjs/storybook#25211] [Help] [answered]
### Summary

So im workin within a monorepo and im trying to host our shared-assets in storybook.  I get these errors:
```
ERROR in ./libs/ui/.storybook/globals.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss) 15:36-85
Module not found: Error: Can't resolve 'assets/images/bg.webp' in 'C:\Users\dev\WebstormProjects\angular-mono\libs\ui\.storybook'
 @ ./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss 8:6-154 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-124 77:0-124 78:22
-29 78:33-47 78:50-64 55:4-68:5
 @ ./libs/ui/.storybook/preview.js 7:0-61
 @ ./storybook-config-entry.js 5:1201-1292 31:2-36:4 31:1186-36:3

ERROR in ./libs/ui/.storybook/globals.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss) 16:36-102
Module not found: Error: Can't resolve '/assets/fonts/edekachalk-regular.woff2' in 'C:\Users\dev\WebstormProjects\angular-mono\libs\ui\.storybook'
 @ ./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss 8:6-154 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-124 77:0-124 78:22
-29 78:33-47 78:50-64 55:4-68:5
 @ ./libs/ui/.storybook/preview.js 7:0-61
 @ ./storybook-config-entry.js 5:1201-1292 31:2-36:4 31:1186-36:3

ERROR in ./libs/ui/.storybook/globals.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss) 17:36-92
Module not found: Error: Can't resolve '/assets/fonts/edekachalk.ttf' in 'C:\Users\dev\WebstormProjects\angular-mono\libs\ui\.storybook'
 @ ./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss 8:6-154 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-124 77:0-124 78:22
-29 78:33-47 78:50-64 55:4-68:5
 @ ./libs/ui/.storybook/preview.js 7:0-61
 @ ./storybook-config-entry.js 5:1201-1292 31:2-36:4 31:1186-36:3

ERROR in ./libs/ui/.storybook/globals.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss) 18:36-94
Module not found: Error: Can't resolve '/assets/fonts/72-Regular.woff2' in 'C:\Users\dev\WebstormProjects\angular-mono\libs\ui\.storybook'
 @ ./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss 8:6-154 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-124 77:0-124 78:22
-29 78:33-47 78:50-64 55:4-68:5
 @ ./libs/ui/.storybook/preview.js 7:0-61
 @ ./storybook-config-entry.js 5:1201-1292 31:2-36:4 31:1186-36:3

ERROR in ./libs/ui/.storybook/globals.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss) 19:36-99
Module not found: Error: Can't resolve '/assets/fonts/72-Regular-full.woff2' in 'C:\Users\dev\WebstormProjects\angular-mono\libs\ui\.storybook'
 @ ./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./libs/ui/.storybook/globals.scss 8:6-154 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-124 77:0-124 78:22
-29 78:33-47 78:50-64 55:4-68:5
 @ ./libs/ui/.storybook/preview.js 7:0-61
 @ ./storybook-config-entry.js 5:1201-1292 31:2-36:4 31:1186-36:3

```

Also when i try and use the @use instead of @import in the shell.scss i get errors saying that no stylesheet could be found for the animations.min.css

### Additional information

```ts 
main.ts
import { StorybookConfig } from '@storybook/angular';

const config: StorybookConfig = {
  framework: '@storybook/angular',
  stories: ['../src/lib/**/*.stories.mdx', '../src/lib/**/*.stories.@(js|jsx|ts|tsx)'],
  staticDirs: [{from:'../../shared-assets', to:'assets'}],
  addons: ['@storybook/addon-essentials', '@storybook/addon-a11y', 'storybook-dark-mode'],

  webpackFinal: async (config, { configType }) => {
    // add your own webpack tweaks if needed
    config.module!.rules!.push({
      test: /\.css$/,
      use: ['style-loader', 'css-loader']
    });

    return config;
  },

  docs: {
    autodocs: true
  }
};

export default config;
```
```js
preview.js
import '@fontsource/work-sans/index.css';
import '@fontsource/work-sans/600.css';
import '@fontsource/work-sans/700.css';
import '@fontsource/work-sans/800.css';
import { themes } from '@storybook/theming';

import '!style-loader!css-loader!sass-loader!./globals.scss';

export const parameters = {
  docs: { inlineStories: true },
  darkMode: {
    // Override the default dark theme
    dark: {
      ...themes.dark,
      appBg: '#2f2f2f',
      brandTitle: 'Test',
      brandImage: 'assets/images/test1.webp',
      brandTarget: '_self'
    },
    // Override the default light theme
    light: {
      ...themes.normal,
      appBg: 'white',
      brandTitle: 'Test',
      brandImage: 'assets/images/test2.png',
      brandTarget: '_self'
    },
    current: 'light',
    darkClass: 'dark',
    lightClass: 'light',
    stylePreview: true,
    classTarget: 'html'
  }
};
```
```scss
globals.scss
@use 'libs/test-theme-new/shell';
@use 'libs/test-theme-new/theme';
@use 'libs/test-theme-new/palette';
@use 'libs/test-theme-new/fonts';
@use '../src/lib/cards/styles/card_theme';

$fonts: ('Work Sans', sans-serif);

* {
  box-sizing: border-box;
}

body {
  padding: 0;
  margin: 0;
  font-family: $fonts;
}

```
```scss
_shell.scss
@import 'open-props/animations.min.css';
@import 'open-props/easings.min.css';
@import 'open-props/borders.min.css';
@import 'open-props/media.min.css';
@import 'open-props/shadows.min.css';
@import 'open-props/sizes.min.css';
@import 'open-props/zindex.min.css';
@import 'open-props/colors.min.css';
@import 'open-props/fonts.min.css';
@import 'open-props/colors-hsl.min.css';

* {
  box-sizing: border-box;
}

html,
body {
  width: 100vw;
  height: 100vh;
}

body {
  overflow: hidden;
  padding: 0;
  margin: 0;
  background-color: black;
  background-image: url('assets/images/bg.webp');
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  font-family: 'Fiori72', 'Fiori72full', Arial, Helvica, sans-serif;
}

::-webkit-scrollbar-track {
  background-color: transparent;
}

::-webkit-scrollbar {
  width: 8px;
  height: 8px;
  background-color: transparent;
}

::-webkit-scrollbar-thumb {
  background-clip: padding-box;
  background-color: #707070;
  border-radius: 4px;
}

::-webkit-scrollbar-corner {
  background-color: transparent;
}

.mat-mdc-icon-button {
  font-size: unset !important;
}
```
