### DISCUSSION TITLE
urls in Sass are not resolving in deployment

### DISCUSSION THREAD

**Discussion by alexmkio** [storybookjs/storybook#25482] [Help]
### Summary

I have a Next.js 14.0.4 application utilizing Storybook 7.6.6 and Sass 1.63.3 (should be pretty up-to-date) with assets in /public/ folder and reference them with css like `background-image: url('/assets/image.jpg)`.

The image resolves when I'm using `npm run dev`, `npm run build`, deployment with Vercel, `npm run storybook`, AND `npm run build-storybook`, _but_ when I use either the [bitovi/github-actions-storybook-to-github-pages
](https://github.com/bitovi/github-actions-storybook-to-github-pages) or [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) to deploy it to `
  "homepage": "https://username.github.io/reponame/",` it won't resolve unless I manually change the image path in devtools to `background-image: url('./assets/image.jpg)`.

I am following the documentation for using [Sass](https://storybook.js.org/recipes/sass), [serving static files](https://storybook.js.org/docs/configure/images-and-assets#serving-static-files-via-storybook-configuration), [deploying to GitHub Pages](https://storybook.js.org/docs/sharing/publish-storybook#github-pages), and [deploying to a subpath](https://storybook.js.org/docs/configure/images-and-assets#absolute-versus-relative-paths).

Help!

```
name: Continuous Integration

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node Version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Build Storybook
        id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          path: storybook-static
```

### Additional information

```
import type { StorybookConfig } from "@storybook/nextjs";

const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-onboarding",
    "@storybook/addon-interactions",
    "storybook-addon-rtl",
    "@storybook/addon-mdx-gfm",
  ],
  framework: {
    name: "@storybook/nextjs",
    options: {},
  },
  staticDirs: ["../public"],
  docs: {
    autodocs: "tag",
  },
};
export default config;
```

### Create a reproduction

[https://github.com/alexmkio/storybook-sass-deployment](https://github.com/alexmkio/storybook-sass-deployment)
