### DISCUSSION TITLE
Increase font size by themeing

### DISCUSSION THREAD

**Discussion by ben-hamel** [storybookjs/storybook#25606] [Ideas]
### Describe the solution you'd like

Would like to be able to increase font size of Storybook using something like fontSize: "18px". the font is really small in storybook ui (sidebar, docs, args tables) and would be nice to increase readability in a easy manner. 

### Are you able to assist to bring the feature to reality?

no

**Comment by noranda** [comment]
⬆️  I have been fighting with Storybook docs forever trying to increase the base font size! The default base font size is 16px for all modern browsers, but Storybook uses 14px. It's too small for docs. Storybook theming doesn't seem to provide a way to overwrite this.

The only workaround I've come up with is to add this to my `preview-head.html`. It's ugly, but it works! Would love to get proper support for this.

```html
<style>
  :where(p:not(.sb-anchor, .sb-unstyled, .sb-unstyled p)),
  :where(li:not(.sb-anchor, .sb-unstyled, .sb-unstyled li)) {
    font-size: max(1em, 16px) !important;
  }
</style>
```

**Reply by spikebrehm** [reply]
We tried this, but the `!important` was overriding our component styles, which we can't have.

Storybook folks, it seems like the easiest solution would be to add a `fontSize` theme property alongside `fontBase`.

**Comment by greypants** [comment]
I'm doing this:
```
.sbdocs-content:not(.sb-unstyled) > p {
  font-size: 16px;
}
```

I'm sure I'll need more once docs get beyond just p tags and headers.

Also, instead of preview-head.html, import css in the In my preview.tsx file:

```
// preview.tsx
import "./preview.css";
```

**Comment by yandodov** [comment]
Here's what I'm using and it seems to work great:

```css
.sbdocs.sbdocs-content :where(p:not(.sb-anchor, .sb-unstyled, .sb-unstyled p)),
.sbdocs.sbdocs-content :where(li:not(.sb-anchor, .sb-unstyled, .sb-unstyled li)) {
  font-size: 1em;
  line-height: 1.5;
}

.sbdocs.sbdocs-content :where(p:not(.sb-anchor, .sb-unstyled, .sb-unstyled p)) code,
.sbdocs.sbdocs-content :where(li:not(.sb-anchor, .sb-unstyled, .sb-unstyled li)) code {
  font-size: 1em;
}
```
