### DISCUSSION TITLE
Image snapshot tests fail in CI (test-runner)

### DISCUSSION THREAD

**Discussion by jussibility** [storybookjs/storybook#25999] [Help]
### Summary

I'm using test-runner for image snapshot testing and it seems to work well when running locally but all my snapshots fail when running in Azure Pipelines.

```
Expected image to match or be a close match to snapshot but was 0.03895399305555556% different from snapshot (359 differing pixels).
See diff for details: /home/vsts/work/1/s/__snapshots__/__diff_output__/button--danger-button-diff.png
```
 
 My pipeline contains the following steps after npm ci and some other steps: 
 
```
- script: npm run build-storybook
  displayName: "Build Storybook"

- script: npx playwright install --with-deps
  displayName: "Install Playwright"

- script: npm run test-storybook:ci
  continueOnError: true
  displayName: "Run tests"

- task: PublishTestResults@2
  inputs:
    testResultsFormat: "JUnit"
    testResultsFiles: "junit.xml"
    failTaskOnFailedTests: true
  displayName: "Publish test results"`
```

Where my scrips in package.json are defined like this:

```
    "test-storybook:ci": "concurrently -k -s first -n \"SB,TEST\" -c \"magenta,blue\" \"npx http-server storybook-static --port 6006 --silent\" \"wait-on tcp:6006 && yarn test-storybook --junit --ci\"",
    "build-storybook": "storybook build",
```

How do I see the diff in Azure pipelines so that I can figure out how/why the snapshots differ? I can see the failing tests in the test results tab but the provided diff image links do not work. Do I need to add attachments to my junit file somehow? Or do I need to publish the diff images as pipeline artifacts or what would be a good way to see the images?

### Additional information

storybook 7.6.10
@storybook/test-runner 0.16.0
jest-image-snapshot 6.4.0
