### DISCUSSION TITLE
Theme: Customization Storybook Theme for Skeletons in Docs and Story

### DISCUSSION THREAD

**Discussion by ddecrulle** [storybookjs/storybook#26088] [Help]
### Summary

Hello,

I'm using two themes in Storybook, a light theme and a dark theme. Everything is working fine, except for the customization of the Skeleton in the documentation and stories. `appPreviewBg` apply values only in global loader.
![image](https://github.com/storybookjs/storybook/assets/81740200/e2d8c46f-f3a2-4dad-bcb7-9560c2be6084)

I'm unable to customize these values, which causes a white flash in dark mode (see attached photo). I've tried all the customizable values available at the following link: [link to customizable values](https://github.com/storybookjs/storybook/blob/fd6a748190f09d9fee906357daaead829ca4243f/code/lib/theming/src/types.ts#L13), but I haven't succeeded. Have I missed something?

To work around this issue, I added the following style in the preview-head.html file:

```css
<style>
    body.sb-show-preparing-docs > .sb-wrapper {
        visibility: hidden;
    }

    body .sb-preparing-story {
        visibility: hidden;
    }
</style>
```
However, this is not satisfactory.

Thank you for your help and have a great day!
