### DISCUSSION TITLE
My project uses Chromatic + Storybook, why does every PR include components that have already been reviewed?

### DISCUSSION THREAD

**Discussion by baixiaoyu2997** [storybookjs/storybook#27030] [Help]
### Summary

this PR only add radio component, but ask me to review all components, and other components already been reviewed.

![image](https://github.com/storybookjs/storybook/assets/9149999/ee97016d-8668-4352-bfbb-6a269459063f)

should i set `autoAcceptChanges`  value to `develop` ?

### Additional information

this is my CI file

component-visual-verification.yml :
```
name: Visual Test

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.d.ts'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  changed-files:
    runs-on: self-hosted
    name: changed-files
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            apps/*/pages/**/*.vue
            apps/*/layouts/**/*.vue
            apps/*/components/**/*.vue
            apps/**/assets/**/*
            packages/base/assets/**/*
            packages/base/components/**/*
            packages/base/extends/**/*.css
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          ANY_CHANGED: ${{ steps.changed-files.outputs.any_changed }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            echo Did any files change: ${ANY_CHANGED}
          done

  chromatic:
    name: Run visual tests
    needs: [changed-files]
    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
    uses: ./.github/workflows/chromatic.yml
    secrets: inherit

```
chromatic.yml :
```
# .github/workflows/chromatic.yml
name: Chromatic

on: workflow_call

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-chromatic
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  chromatic:
    name: Chromatic
    runs-on: self-hosted
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 18

      - name: 📥 Install deps
        run: pnpm install

      - name: ⚡ Run chromatic
        uses: chromaui/action@latest
        # Chromatic GitHub Action options
        with:
          workingDir: apps/storybook
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          # exitOnceUploaded: true
          # onlyChanged: true # NOTE: do not use onlyChanged with pull_request event, https://www.chromatic.com/docs/setup-turbosnap/#github-pull_request-triggers
          buildScriptName: 'build'
          autoAcceptChanges: 'main'
          skip: '@(renovate/**|dependabot/**)'

```
