### ISSUE TITLE
How to run on non-root url?

### ISSUE THREAD

**Issue by kariasbolster** [storybookjs/storybook#10356]
I want to deploy storybook-react on a kubernetes cluster. the load balancer will route traffic from /storybook to the storybook service. So how can I make it run on /storybook instead of root url?

**Comment by yannbf** [comment]
Hey @kariasbolster, that's a very interesting question! Although I think it's a more generic multi-app with kubernetes question, not necessarily related to storybook.

So if you follow the steps [described here](https://storybook.js.org/docs/basics/exporting-storybook/), you should have the statics for your storybook project in a folder like `storybook-static`. From there, I think it's a matter of creating a service that exposes those statics as an app and [define a ingress controller](https://medium.com/kubernetes-tutorials/deploying-traefik-as-ingress-controller-for-your-kubernetes-cluster-b03a0672ae0c) that points the `/storybook` to that service!

I'm not 100% certain, but maybe some config like this?
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /storybook
        backend:
          serviceName: storybookService 
          servicePort: 80
```
