### ISSUE TITLE
No config file for hostname

### ISSUE THREAD

**Issue by ozee31** [storybookjs/storybook#11314]
**Describe the bug**
When I start Storybook with docker i have an error :

`No config file for hostname :`

It's work directly without docker http://localhost:6006/.

**To Reproduce**

- docker-compose.yml

```yml
 
version: "3"

services:
	storybook:
    build: .c42/docker/node
    networks:
      - traefik
      - default
    ports:
      - 6006
    volumes:
      - ./src/client/:/project
      - .npm:/.npm
      - $SSH_AUTH_SOCK:/ssh-agent
    command: yarn storybook
    labels:
      - traefik.frontend.rule=Host:story.project.test
      - traefik.port=6006
```

- Dockerfile

```
FROM node:12

RUN mkdir -p /root/.ssh
RUN ssh-keyscan -H github.com >> /root/.ssh/known_hosts

ENV SSH_AUTH_SOCK=/ssh-agent

WORKDIR /project
VOLUME ["/project"]

RUN yarn install
```

- package.json

```json
"scripts": {
  "storybook": "start-storybook -p 6006",
},
```

- .storybook/addons.js

```js
import '@storybook/addon-actions/register';
import '@storybook/addon-storysource/register';
import '@storybook/addon-a11y/register';

```

- .storybook/config.js

```js
import React from "react";
import { configure, addDecorator } from "@storybook/react";
import centered from "@storybook/addon-centered/react";
import { withA11y } from "@storybook/addon-a11y";
import "@storybook/addon-console";
import {
  StylesProvider,
  ThemeProvider as MuiThemeProvider
} from "@material-ui/styles";
import { ThemeProvider } from "styled-components";
import theme from "../src/theme/Theme";

import "../src/theme/fontface.css";

// automatically import all files ending in *.stories.js
const req = require.context("../src", true, /.stories.js$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

// should only be added once
// best place is in config.js
addDecorator(withA11y);

// automatically center components
addDecorator(centered);

addDecorator(story =>
  React.createElement(
    ThemeProvider,
    { theme },
    React.createElement(
      StylesProvider,
      {
        injectFirst: true
      },
      React.createElement(MuiThemeProvider, { theme: theme }, story())
    )
  )
);

configure(loadStories, module);

```

- .storybook/webpack.config.js

```js
module.exports = function ({ config }) {
  config.module.rules.push({
    test: /\.stories\.jsx?$/,
    loaders: [require.resolve('@storybook/addon-storysource/loader')],

  });

  return config;
};

```

**System:**
Storybook version : "@storybook/react": "^5.3.19".
