### ISSUE TITLE
Configuring assets when deploying storybook in subpath

### ISSUE THREAD

**Issue by dmudro** [storybookjs/storybook#12444]
What is the best approach for configuring SB when hosted in a subfolder? GitHub or Gitlab pages typically host static pages in a subfolder

https://www.example.com/foo/storybook

JSX in my react components points to assets in absolute paths:

```
(
  <img src="/assets/image.png" />
)
```

This is not going to work in an exported storybook as it would try and load 
`https://www.example.com/assets/image.png` (incorrect) 
instead of 
`https://www.example.com/foo/storybook/assets/image.png` (desired)

`<base>` tag is of no use as it gets ignored for absolute paths (`src="/assets/image.png"` in my example)

Any recommendations please? I cannot change the source react components so following solutions are not doable:
- upload assets to CDN and request them in Storybook
- `import` images in React components and let WebPack do bundling
- remove `/` from the start of the image path

Perhaps I am missing something or [the docs](https://storybook.js.org/docs/react/configure/images-and-assets#absolute-versus-relative-paths) could be improved. Most of the examples are too simple and the mention of `base` is slightly vague.

A similar (same?) issue is described [here](https://github.com/storybookjs/storybook/issues/10025) with no resolution.

**Comment by persocon** [comment]
same issue 🤷 with all storybook assets for their UI

**Comment by lpbayliss** [comment]
I've also come across this same problem.
The `html.index` page can be loaded at `https://example.com/storybook` but the script files are being fetched from `https://example.com/[script-here]`. Being relative paths the `<base>` element does nothing.

**Comment by sarahbethfederman** [comment]
You likely need to set the publicPath in your webpack config to the CDN url where your assets are hosted
```
  webpackFinal: async (config) => {
    config.output.publicPath = YOUR_URL;
    return config;
  },

```

**Comment by xcv58** [comment]
Thanks @sarahbethfederman,

There is a key difference when I applied the webpack `publicPath`, which removes the Storybook [Toolbar](https://storybook.js.org/docs/react/get-started/browse-stories#toolbar) from the output app.

And the [`--docs`](https://storybook.js.org/docs/react/api/cli-options#build-storybook) option of `build-storybook` will impact the output. The reproduce repo and demo links are here: https://github.com/xcv58/storybook-issue-12444#resolution

Post here in case anyone has a similar issue.

**Comment by jonniebigodes** [comment]
Closing this issue down as the `staticDirs` option solves this. As a reference here's a [deployment](https://github.com/jonniebigodes/example-sb-deploy-assets) and repo [here](https://github.com/jonniebigodes/example-sb-deploy-assets). Feel free to comment with a use case so that this issue can be re-opened and triaged.

**Comment by devonpis** [comment]
@jonniebigodes in your ExampleComponent 
```
<img src="assets/one.jpg" alt="example one" width={300} height={300} />
```
your solution did solve `src="assets/one.jpg"`, but doesn't solve `src="/assets/one.jpg"` (where is the OP having problem)

or are you suggesting to use relative path for loading assets?

**Comment by mcAnastasiou** [comment]
Is there any solution to this regarding src="/assets/one.jpg"

**Comment by bmitchinson** [comment]
Using storybook-build worked fine to deploy the preview application, but img assets were broken in my components when attempting to reference `/assets/test.img`. That would request `bmitchinson.github.io/assets/test.img` instead of `bmitchinson.github.io/notion-publish-tool/assets/test.img`

I ended up using the `string-replace-loader` webpack plugin, in the event GH_PAGES is set for storybook builds.

this way I can continue to use root URL addresses in svelte components, but account for the added gh pages repo route. This rule is only applied in GH_PAGES builds of story book, 

`.storybook/main.js`
```
webpackFinal: async (config) => {
        if (process.env.GH_PAGES) {
            config.module.rules.push({
                test: /.svelte$/,
                loader: 'string-replace-loader',
                options: {
                    search: '/assets/',
                    replace: '/notion-publish-tool/assets/',
                },
            });
        }
        return config;
    },
```

`.github/workflows/deploy_storybook.yml`
```
name: Deploy Storybook

on:
    workflow_run:
        workflows: ['Static Analysis']
        branches: [main]
        types:
            - completed

jobs:
    Build-and-Deploy-Storybook:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.14.0'
                  cache: 'npm'
            - run: npm ci
            # GH_PAGES set here to trigger the conditional webpack rule
            - run: GH_PAGES=true npm run storybookbuild
            - uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: storybook_build
```

Example repo: https://github.com/bmitchinson/notion-publish-tool
