### ISSUE TITLE
Question: Does a plugin exists to simulate safe-area-inset margins ?

### ISSUE THREAD

**Issue by Aarbel** [storybookjs/storybook#12852]
# Does a plugin exists to simulate safe-area-inset margins with storybook ? 

Typicaly for tablets or mobile devices.

# Goal

Don't waste time testing on the devices, but test directly in storybook

Thanks a lot for your help !

**Comment by Aarbel** [comment]
Maybe a great enhancement for [viewport addon](https://storybook.js.org/docs/react/essentials/viewport)

**Comment by shilman** [comment]
PRs welcome for `addon-viewport`!

**Comment by Aarbel** [comment]
@shilman i can do it, but i don't know if we can force safe-area-inset env variables in an iframe, do you have some documentation about it ?

**Comment by Aarbel** [comment]
@shilman

Just tried with:

```JS
document.documentElement.style.setProperty("safe-area-inset-top","20px");
```

But it doesn't work, safe-area-inset variables are set by user agent. Is there a way to hack it ?

Thanks a lot for your help

**Comment by Aarbel** [comment]
@shilman ?

**Comment by Aarbel** [comment]
@shilman up ;)

**Comment by shilman** [comment]
Sorry, I don't know the answer 🤷

**Comment by Aarbel** [comment]
Cf https://stackoverflow.com/questions/56499416/setting-css-env-variables-programmatically-using-javascript

@jantimon maybe you can help on this ?

**Comment by MichaelArestad** [comment]
@shilman I am unfamiliar with any addons that might do this. I suspect more research needs to be done before building it.  Does the size of the inset areas change per device? What would we need to do in the code to replicate the behavior of an active inset area?

**Comment by MichaelArestad** [comment]
@Aarbel That's exactly what got me thinking about the differences in inset behavior per device. 🤔

**Comment by Aarbel** [comment]
After testing, env() fallback doesn't seem to work well on most browsers, because they actually set the env variable as "0px" that means the value exists.

Something like that works better:

```CSS
.storybook-iframe {
    --storybook-safe-area-inset-top: 32px;
}

:root {
    --safe-area-inset-top: max(env(safe-area-inset-top) , var(--storybook-safe-area-inset-top));
}

.myclass {
    padding-top: var(--safe-area-inset-top);
}

```
