### ISSUE TITLE
Should the backgrounds addon respect prefers-reduced-motion?

### ISSUE THREAD

**Issue by ahuth** [storybookjs/storybook#13612]
**Describe the bug**
The backgrounds addon sets a transition on the applied background, so that it fades in and out.

Should it take `prefers-reduced-motion` into account, and not transition if someone sets the related OS and browser settings?

**To Reproduce**

1. Configure a background for a story. For how to do that, see the [backgrounds documentation](https://storybook.js.org/docs/react/essentials/backgrounds).
2. Run storybook
3. For the story, select a background

**Expected behavior**
- If the user has configured their OS to reduce motion, the transition should not happen.
- If the user has not configured their OS to reduce motion, the transition should happen.

**Screenshots**
![stepbar-fade](https://user-images.githubusercontent.com/2503289/104252433-ead12e80-5426-11eb-83c9-2a912d83274c.gif)

**Additional context**
We can already prevent the transition with some custom CSS:

```css
@media (prefers-reduced-motion) {
  .sb-show-main {
    transition: none !important; /* !important needed to counter inline style */
  }
}
```

I'm wondering if we should build this in to the addon, though. I can put up a pull request to do so if it's what we want.
