### ISSUE TITLE
Yarn 2 compatibility: undeclared peerDependencies (non-breaking)

### ISSUE THREAD

**Issue by DemianX0** [storybookjs/storybook#14838]
**Describe the bug**

`yarn install` (Yarn 2 - Berry) produces this output. These are warnings only, not breaking:
```
➤ YN0000: ┌ Resolution step
...
➤ YN0002: │ @storybook/aurelia@npm:6.2.9 [61d6c] doesn't provide typescript@* requested by ts-loader@npm:6.2.2
➤ YN0002: │ @storybook/core@npm:6.2.9 [14add] doesn't provide webpack@* requested by @storybook/core-client@npm:6.2.9
➤ YN0002: │ @storybook/core@npm:6.2.9 [61d6c] doesn't provide webpack@* requested by @storybook/core-client@npm:6.2.9
➤ YN0002: │ @storybook/html@npm:6.2.9 [61d6c] doesn't provide webpack@^4.0.0 || ^5.0.0 requested by html-loader@npm:1.3.2
➤ YN0002: │ @storybook/core@npm:6.2.9 [02201] doesn't provide webpack@* requested by @storybook/core-client@npm:6.2.9
➤ YN0002: │ @storybook/marionette@npm:6.2.9 [61d6c] doesn't provide webpack@^4.0.0 || ^5.0.0 requested by html-loader@npm:1.3.2
➤ YN0002: │ @storybook/core@npm:6.2.9 [bf9dd] doesn't provide webpack@* requested by @storybook/core-client@npm:6.2.9
➤ YN0002: │ vue-docgen-api@npm:4.38.1 doesn't provide vue@3.0.11 requested by @vue/compiler-sfc@npm:3.0.11
➤ YN0002: │ @storybook/vue@npm:6.2.9 [61d6c] doesn't provide typescript@* requested by ts-loader@npm:8.2.0
➤ YN0002: │ @storybook/core@npm:6.2.9 [dae8b] doesn't provide webpack@* requested by @storybook/core-client@npm:6.2.9
➤ YN0002: │ @storybook/vue3@npm:6.2.9 [61d6c] doesn't provide typescript@* requested by ts-loader@npm:8.2.0
➤ YN0002: │ @storybook/core@npm:6.2.9 [9187c] doesn't provide webpack@* requested by @storybook/core-client@npm:6.2.9
...
```

**To Reproduce**

In a temporary folder...
```
yarn set version berry
yarn init
yarn add -D @storybook/core @storybook/aurelia @storybook/html @storybook/marionette @storybook/vue @storybook/vue3
```
Check output for YN0002 warnings, skip those concerning <folder name>@workspace
Thanks to @spiltcoffee  https://github.com/storybookjs/storybook/issues/11397#issuecomment-830063886  https://github.com/storybookjs/storybook/issues/11397#issuecomment-830076079

**Temporary fix**

Create `.yarnrc.yml` next to package.json:
```
packageExtensions:
  "@storybook/core@*":
    peerDependencies:
      webpack: "*"
  "@storybook/html@*":
    peerDependencies:
      webpack: "^4.0.0 || ^5.0.0"
  "@storybook/marionette@*":
    peerDependencies:
      webpack: "^4.0.0 || ^5.0.0"
  "@storybook/aurelia@*":
    peerDependencies:
      typescript: "*"
  "@storybook/vue@*":
    peerDependencies:
      typescript: "*"
  "@storybook/vue3@*":
    peerDependencies:
      typescript: "*"
  "vue-docgen-api@*":
    peerDependencies:
      vue: "^3.0.11"
```
These are the peerDependencies that need to be added to the respective projects. `vue-docgen-api` is not the concern of storybook.

**System**
  OS: Windows 8.1 6.3.9600
Binaries:
  Node: 15.7.0
  Yarn: 2.0.0-rc.27
  npm: 7.10.0

**Additional context**

Spin-off of https://github.com/storybookjs/storybook/issues/11397
