### ISSUE TITLE
When using chakra ui inside storybook the colors and some styles are not resolved

### ISSUE THREAD

**Issue by prasenjit-net** [storybookjs/storybook#15858]
**Describe the bug**
I am using the latest version of chakra UI with the latest version of the storybook. My application colors and styles are fine but when I see them in the storybook, none of the style tokens get resolved from the theme. I can see the token intact in the resulting CSS.
```css
.css-19uf7in {
    padding-inline-start: 4px;
    padding-inline-end: 4px;
    background: blue.500;
    color: red.100;
}
```
But when using in application it resolved properly in css
```css
.css-16dkpvs {
    padding-inline-start: var(--chakra-space-4);
    padding-inline-end: var(--chakra-space-4);
    background: var(--chakra-colors-blue-500);
    color: var(--chakra-colors-red-100);
}
```

**To Reproduce**
Create a simple application using chakra UI and add any simple element with some style and color. Use `npx sb init` to init storybook. Add chakra provider in both application and story.
An example can be found here https://github.com/prasenjit-net/chakra-bug

**System**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 91.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.3.7 => 6.3.7 
    @storybook/addon-essentials: ^6.3.7 => 6.3.7 
    @storybook/addon-links: ^6.3.7 => 6.3.7 
    @storybook/react: ^6.3.7 => 6.3.7 

**Additional context**
**Dependency Info**
```json
{
  "dependencies": {
    "@chakra-ui/react": "^1.6.6",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "framer-motion": "^4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@storybook/addon-actions": "^6.3.7",
    "@storybook/addon-essentials": "^6.3.7",
    "@storybook/addon-links": "^6.3.7",
    "@storybook/react": "^6.3.7",
    "babel-loader": "^8.2.2",
    "parcel": "^2.0.0-nightly.800"
  }
}
```
