### ISSUE TITLE
Storybook's own styles are overwriting my component styles

### ISSUE THREAD

**Issue by Braweria** [storybookjs/storybook#16545]
**Describe the bug**
I have an h2 element with styles:  

```css
h2 {
  display: block;
}
```

But because of Storybook's own styling in the DOM, it becomes

```css
h2 {
  display: inline-block;
}
```

And it messes everything up.

**To Reproduce**
Just have a h2 Element with styles applied, like in the example above.

**System**
// Please paste the results of `npx sb@next info` here.

**Additional context**
Writing my stories in MDX. This issue appears in the Docs and the Canvas panel.
