### ISSUE TITLE
Unresolved dependency

### ISSUE THREAD

**Issue by GitProdEnv** [storybookjs/storybook#16715]
Installing the `storybook-addon-apollo-client` addon gives me following error, when I want to start storybook:

`Error: storybook-addon-apollo-client tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

I'm using Yarn 2 Berry PnP. 

This is being resolved by adding

```yaml
# .yarnrc.yml
'storybook-addon-apollo-client@*':
    dependencies:
      'tslib': '*'
```
to the .yarnrc.yml file

This is only a Yarn 2 issue, but I just want to mention it. Maybe you can add tslib as a required dependency!

Cheers
