### ISSUE TITLE
Storybook 6.4: storyStoreV7 does not respect component id

### ISSUE THREAD

**Issue by fabiradi** [storybookjs/storybook#16713]
**Describe the bug**
Manually set `id` in _story meta_ is not respected, when `features.storyStoreV7` is set. It _does_ work with the regular store (as on v6.3 and earlier)

- Storybook 6.4-rc3 (still) works great with an `id` set for a story to have a **permalink** that _will not change_ based on the location of the story (this may be essential for some use cases).

```javascript
// src/stories/Button.stories.tsx
export default {
  title: 'Example/Button',
  component: Button,
  id: 'mybutton', // 🚨 This is important
} as ComponentMeta<typeof Button>
```

### How the ID is used

```javascript
// Generated story ID based on "title" (no "id" property set)
example-button--primary

// Story ID based on property "id"
mybutton--primary
```

### What is not working?

If you want to use the new [v7 story store](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#using-the-v7-store), the **manually set IDs** seems to be ignored.

```javascript
// .storybook/main.js
module.exports = {
  // ...
  features: {
    storyStoreV7: true, // 🚨 activating this casues the conflict
  },
};
```

**To Reproduce**
* Repository: https://github.com/fabiradi/storybook-v6.4-story-ids
* Published: https://fabiradi.github.io/storybook-v6.4-story-ids/

**System**
```yaml
Environment Info:

  System:
    OS: macOS 11.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.npm-global/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.0-rc.3 => 6.4.0-rc.3 
    @storybook/addon-essentials: ^6.4.0-rc.3 => 6.4.0-rc.3 
    @storybook/addon-links: ^6.4.0-rc.3 => 6.4.0-rc.3 
    @storybook/node-logger: ^6.4.0-rc.3 => 6.4.0-rc.3 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.0-rc.3 => 6.4.0-rc.3 
    @storybook/storybook-deployer: ^2.8.10 => 2.8.10 
```
![storystorev7-id-conflict](https://user-images.githubusercontent.com/5428213/142197449-8ac029f0-9681-4e6f-b5d8-8285385b03c2.png)
