### ISSUE TITLE
Preview component hidden content obscured (Firefox)

### ISSUE THREAD

**Issue by m7kvqbe1** [storybookjs/storybook#16714]
**Describe the bug**

Storybook Docs Stories in Firefox obscures hidden content (such as a Context Menu or Date Picker component sheet). 

Appears to be working as expected in Chrome.

**To Reproduce**

Check any component story that has a floating sheet:

<img width="1427" alt="Screenshot 2021-11-17 at 11 05 19" src="https://user-images.githubusercontent.com/48086589/142201493-3058e892-42bb-45d9-90ec-58070b1b047f.png">

**System**

```
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 94.0.1
    Safari: 15.1
```

**Additional context**

https://github.com/storybookjs/storybook/issues/8928

We are currently hacking around this with style overides within `preview-head.html`:

```css
#docs-root .docs-story {
  overflow: visible;
}

#docs-root .docs-story > div:last-child {
  bottom: 10px;
}

#docs-root .docs-story > div:first-child > div:first-child {
  transform: none;
  height: auto;
}
```
