### ISSUE TITLE
Yarn Berry is still reporting incorrectly met peer dependencies

### ISSUE THREAD

**Issue by spiltcoffee** [storybookjs/storybook#16814]
**Describe the bug**
#14838 was closed, but there still appears to be incorrectly met peer dependency messages (YN0002) being emitted by Yarn Berry related to Storybook packages:

```
$ yarn add -D @storybook/ember @storybook/html @storybook/server @storybook/svelte @storybook/vue @storybook/vue3 @storybook/web-components @storybook/addon-interactions @storybook/addon-google-analytics @storybook/addon-graphql
➤ YN0000: ┌ Resolution step
...
➤ YN0002: │ @storybook/ember@npm:6.4.0 [7ea29] doesn't provide webpack (p76f76), requested by @storybook/core
➤ YN0002: │ @storybook/html@npm:6.4.0 [7ea29] doesn't provide webpack (pd0599), requested by @storybook/core
➤ YN0002: │ @storybook/html@npm:6.4.0 [7ea29] doesn't provide webpack (p89e4b), requested by html-loader
➤ YN0002: │ @storybook/server@npm:6.4.0 doesn't provide webpack (p987d4), requested by @storybook/core
➤ YN0002: │ @storybook/svelte@npm:6.4.0 [7ea29] doesn't provide webpack (p8e2f4), requested by @storybook/core
➤ YN0002: │ @storybook/vue3@npm:6.4.0 [7ea29] doesn't provide typescript (p67f05), requested by ts-loader
➤ YN0002: │ @storybook/vue@npm:6.4.0 [7ea29] doesn't provide typescript (p78e10), requested by ts-loader
➤ YN0002: │ @storybook/web-components@npm:6.4.0 [7ea29] doesn't provide @babel/core (p370e6), requested by @babel/plugin-syntax-dynamic-import
➤ YN0002: │ @storybook/web-components@npm:6.4.0 [7ea29] doesn't provide @babel/core (pe3165), requested by @babel/plugin-syntax-import-meta
➤ YN0002: │ @storybook/web-components@npm:6.4.0 [7ea29] doesn't provide @babel/core (p244da), requested by @babel/preset-env
➤ YN0002: │ @storybook/web-components@npm:6.4.0 [7ea29] doesn't provide @babel/core (p26f62), requested by babel-plugin-bundled-import-meta
➤ YN0002: │ @storybook/web-components@npm:6.4.0 [7ea29] doesn't provide webpack (pf0882), requested by @storybook/core
➤ YN0002: │ @storybook/instrumenter@npm:6.4.1 doesn't provide react (p83ff1), requested by @storybook/addons
➤ YN0002: │ @storybook/instrumenter@npm:6.4.1 doesn't provide react-dom (p025c5), requested by @storybook/addons
➤ YN0002: │ @storybook/addon-google-analytics@npm:6.2.9 [b0f9c] doesn't provide prop-types (p44043), requested by react-ga
➤ YN0060: │ @storybook/addon-graphql@npm:6.2.9 [b0f9c] provides graphql (pe3cae) with version 15.7.2, which doesn't satisfy what graphiql and some of its descendants request
...
➤ YN0000: └ Completed in 13s 37ms
```

**To Reproduce**
As per the previous issue, in a temporary folder:
```
$ yarn set version berry
$ yarn init
$ yarn add -D @storybook/ember @storybook/html @storybook/server @storybook/svelte @storybook/vue @storybook/vue3 @storybook/addon-interactions @storybook/addon-google-analytics @storybook/addon-graphql
```

_Note: the `yarn add` command above only lists the packages still emitting YN0002 messages_

**Temporary Fix**
As per the previous issue, in a package using one of these @storybook/apps, it is generally possible to clear the errors by using the [`packageExtensions`](https://yarnpkg.com/configuration/yarnrc#packageExtensions) field in the `.yarnrc.yml`.

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.1.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)
```

**Additional context**
Follow up of #14838

**Comment by JorisAerts** [comment]
I had to add these in order to make it work:

```
packageExtensions:

  "@storybook/core-server@*":
    dependencies:
      "@storybook/manager-webpack5": "*"

  "@storybook/builder-webpack5@*":
    dependencies:
      "react": "16.14.0"
      "react-dom": "16.14.0"

  "@storybook/manager-webpack5@*":
    dependencies:
      "react": "16.14.0"
      "react-dom": "16.14.0"


  # since Storybook 6.4... :-(

  axe-core@*:
    dependencies:
      process: "*"

  es6-shim@*:
    dependencies:
      process: "*"

  path-browserify@*:
    dependencies:
      process: "*"

  es-get-iterator@*:
    dependencies:
      process: "*"
```

**Comment by spiltcoffee** [comment]
@JorisAerts if you're adding `dependencies` into your `packageExtensions` key, you should instead be adding these as actual dependencies in your package, e.g. `yarn add -D react react-dom` for the react dependencies.

Also, the ones you've listed that are not `@storybook` related would best be pushed to those individual projects if they are in fact an issue, since  there's little to nothing that this project can do about it.

**Comment by spiltcoffee** [comment]
Found a couple of peer dependency issues in the addons.

```
$ yarn add -D @storybook/addon-interactions @storybook/addon-google-analytics @storybook/addon-graphql
➤ YN0000: ┌ Resolution step
...
➤ YN0002: │ @storybook/instrumenter@npm:6.4.1 doesn't provide react (p83ff1), requested by @storybook/addons
➤ YN0002: │ @storybook/instrumenter@npm:6.4.1 doesn't provide react-dom (p025c5), requested by @storybook/addons
➤ YN0002: │ @storybook/addon-google-analytics@npm:6.2.9 [b0f9c] doesn't provide prop-types (p44043), requested by react-ga
➤ YN0060: │ @storybook/addon-graphql@npm:6.2.9 [b0f9c] provides graphql (pe3cae) with version 15.7.2, which doesn't satisfy what graphiql and some of its descendants request
...
➤ YN0000: └ Completed in 13s 37ms
```

**Comment by marvinroger** [comment]
I tried with the latest 7.0.0-beta.7 beta, and there are still issues:

> ➤ YN0002: │ @storybook/cli@npm:7.0.0-beta.7 doesn't provide react (p8518b), requested by @storybook/core-server
➤ YN0002: │ @storybook/cli@npm:7.0.0-beta.7 doesn't provide react-dom (p5b776), requested by @storybook/core-server
➤ YN0002: │ @storybook/codemod@npm:7.0.0-beta.7 doesn't provide @babel/preset-env (p17cec), requested by jscodeshift
➤ YN0002: │ @storybook/react-vite@npm:7.0.0-beta.7 [93ab6] doesn't provide typescript (p51277), requested by @joshwooding/vite-plugin-react-docgen-typescript

I was able to silence the warning with:

```yaml
packageExtensions:
  "storybook@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/cli@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/codemod@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@storybook/react-vite@*":
    peerDependencies:
      "typescript": "*"
```

Note that it's not a yarn specific issue, it highlights real peer dependency issues.
The proper fix would probably to add the above peerDependencies to the respective packages.
