### ISSUE TITLE
Generate a pull-request friendly storybook-docs? 

### ISSUE THREAD

**Issue by Nullpo** [storybookjs/storybook#16830]
**Is your feature request related to a problem? Please describe**

Currently, I want in each version of my code there is available the code generated by build-storybook, but the command creates +30 different files, making difficult to differentiate in a pull/merge request the autogenerated code with the code created by our developers. Also, the generated code is created with hashes in their name.

**Describe the solution you'd like**

It will be good if there is a way to generate the docs in a single file, like stryker.js does with the 'mutation coverage' report. Or a way to dinamically load the content (i.e: a lib that exposes something like 'render(id, [array of story files]).   

**Are you able to assist to bring the feature to reality?**
I'm interested in this feature, so maybe yeah if someone helps me giving to me some tips about how to start. I'm currently working as a software developer :).

**Additional context**

In the situation of my company, we don't have a flexible CI model (like github actions) so adding a new step is reeeally dificult for us. So I made a post-commit script with husky for this. After seeing this issue, I searched solutions without success... 

Thank you for your time, and sorry for my bad english. Your product is great! 🎉

**Comment by shilman** [comment]
Hi @Nullpo. This hasn't come up before because we don't recommend checking the built storybook into your repository and instead recommend building it in CI. I understand that this is not possible in your case, but I don't think it's realistic to add this feature to Storybook's core.

**Comment by JorisAerts** [comment]
I had to add these in order to make it work:

```
packageExtensions:

  "@storybook/core-server@*":
    dependencies:
      "@storybook/manager-webpack5": "*"

  "@storybook/builder-webpack5@*":
    dependencies:
      "react": "16.14.0"
      "react-dom": "16.14.0"

  "@storybook/manager-webpack5@*":
    dependencies:
      "react": "16.14.0"
      "react-dom": "16.14.0"


  # since Storybook 6.4... :-(

  axe-core@*:
    dependencies:
      process: "*"

  es6-shim@*:
    dependencies:
      process: "*"

  path-browserify@*:
    dependencies:
      process: "*"

  es-get-iterator@*:
    dependencies:
      process: "*"
```
