### ISSUE TITLE
Fresh Svelte Storybook project is not loading, printing garbage to CLI

### ISSUE THREAD

**Issue by mattfysh** [storybookjs/storybook#17181]
**Describe the bug**

1. Garbage characters are being printed when attempting to `npm run storybook`
1. Page does not load, stuck with infinite loading loop
1. Only way forward is to CTRL+C terminate the storybook process

![image](https://user-images.githubusercontent.com/470258/148708906-ba77d20b-0337-48ba-89a6-2c92c54aa586.png)

**To Reproduce**

```sh
# Create a new Svelte app
npx degit sveltejs/template my-svelte-project
cd my-svelte-project
npm install

# Install Storybook
npx sb init
# This also does not work:
# npx sb@next init

# Run Storybook
npm run storybook
```

**System**

```yaml
  System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 17.3.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 15.2
```
