### ISSUE TITLE
addon-controls not working with addon-docs enabled (using addon-essentials + Vue 3)

### ISSUE THREAD

**Issue by spacedawwwg** [storybookjs/storybook#17350]
**Describe the bug**
addon-controls not working with addon-docs is enabled (using addons-essentials)

**To Reproduce**
Set up Vue 3 storybook with addon-essentials enabled.

**System**
```YAML
  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 3.1.1 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Edge: 97.0.1072.69
    Firefox: 96.0.2
    Safari: 15.2
  npmPackages:
    @storybook/addon-a11y: 6.4.14 => 6.4.14
    @storybook/addon-essentials: 6.4.14 => 6.4.14 
    @storybook/vue3: 6.4.14 => 6.4.14 
```

**Additional context**

WITH default plugin

```JS
module.exports = {
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',
  ],
  core: {
    builder: 'storybook-builder-vite',
  },
  framework: '@storybook/vue3',
  ...
}
```
![image](https://user-images.githubusercontent.com/1691867/151336798-4edf1387-74a0-449f-ad13-8391568a0707.png)

With docs addon disabled

```JS
module.exports = {
  addons: [
    {
      name: '@storybook/addon-essentials',
      options: {
        docs: false
      }
    },
    '@storybook/addon-a11y',
  ],
  core: {
    builder: 'storybook-builder-vite',
  },
  framework: '@storybook/vue3',
  ...
}
```
![image](https://user-images.githubusercontent.com/1691867/151337702-e8d544b0-a9b0-4da1-a91b-6eea0d55db22.png)
