### ISSUE TITLE
Change actions/checkout@v1 to v2 of chromatic.yml 

### ISSUE THREAD

**Issue by dmc31a42** [storybookjs/storybook#17410]
**Is your feature request related to a problem? Please describe**
Prevent mistake like #17408

**Describe the solution you'd like**
, suggest change actions/checkout@v1 to v2 and add lfs option in `storybook/docs/snippets/common/chromatic-github-action.js.mdx`
From:
```yml
      - uses: actions/checkout@v1
```
To: 
```yml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
```

**Describe alternatives you've considered**
If want to use lfs, suggest to use v2 in `docs/sharing/publish-storybook.md` .

**Are you able to assist to bring the feature to reality?**
yes, I can

**Additional context**
N/A
