### ISSUE TITLE
Yarn 3 PnP fails to run with @storybook/addon-storyshots@6.5.6 with TypeScript

### ISSUE THREAD

**Issue by wegry** [storybookjs/storybook#18392]
**Describe the bug**

Without

```yaml
# .yarnrc.yml
packageExtensions:
  "@storybook/addon-storyshots@6.5.6":
    dependencies:
      # https://github.com/storybookjs/storybook/pull/9536/files
      "@types/webpack-env": "1.16.3"
```

Running typescript@4.7.2 will fail to load `@types/webpack-env`.

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

Using yarn@3.2.1 with PnP enabled, run `tsc` from `typescript@4.7.2` on a project with `@storybook/addon-storyshots@6.5.6` installed.

**System**
```
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.1 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Safari: 15.5
 ```
**Additional context**
