### ISSUE TITLE
Storybook doesn't work with yarn PnP

### ISSUE THREAD

**Issue by jpzwarte** [storybookjs/storybook#18435]
So when using yarn PnP, `start-storybook` won't work because of incorrect dependencies. The following is required to even start:

```yaml
packageExtensions:
  "babel-loader@*":
    dependencies:
      "@babel/core": "^7"
  "@storybook/router@*":
    dependencies:
      "util": "^0.12.4"
  "@storybook/ui@*":
    dependencies:
      "util": "^0.12.4"
  "@storybook/web-components@*":
    dependencies:
      "babel-loader": "^8"
```

After this, it will start, but it will hang (using the webpack5 builder). I'm still creating this issue, so the info does not get lost.
