### ISSUE TITLE
Random timeouts @storybook/addon-storyshots-puppeteer

### ISSUE THREAD

**Issue by tduaniOEV** [storybookjs/storybook#18794]
Hello everyone! 

In one of my NextJS recent projects, we decided to use imageSnapshot together with Storybook, to test our components.
Most of the time we have no problems with the snapshot tests, and all of the tests pass, but sometimes random tests fail due to timeout, with the following error message: 

```typescript
 FAIL  tests/unit/__tests__/components/Storyshots.test.js (29.487 s)
  ● Image snapshots › BannerComponent › Banner

    thrown: "Exceeded timeout of 15000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      33 | });
      34 |
    > 35 | initStoryshots({
         | ^
      36 |   suite: 'Image snapshots',
      37 |   test: imageSnapshot({
      38 |     getCustomBrowser: async () => {

      at snapshotTest (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:29:9)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:38:17
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:37:22
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:36:9
      at snapshotTestSuite (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:35:5)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:52:9
          at Array.forEach (<anonymous>)
      at Object.snapshotsTests [as default] (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:51:10)
      at Object.nextFn (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js:66:45)
      at node_modules/synchronous-promise/index.js:217:29
          at Array.forEach (<anonymous>)
      at SynchronousPromise._runResolutions (node_modules/synchronous-promise/index.js:214:19)
      at SynchronousPromise.then (node_modules/synchronous-promise/index.js:67:10)
      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js:40:66)
      at Object.<anonymous> (tests/unit/__tests__/components/Storyshots.test.js:35:1)
```

Our initStoryshot looks like this: 
```typescript
initStoryshots({
  suite: 'Image snapshots',
  test: imageSnapshot({
    getCustomBrowser: async () => {
      const browser = await playwright.chromium.launch();
      return await browser.newContext({
        viewport: {
          width: 800,
          height: 600
        }
      });
    },
    getMatchOptions,
  }),
});
```

After looking at the Docs, I tried to raise the timeout to 30sec with `testTimout: 30_0000`, but then I received a rather different error message, that might be better reflecting on where the problem lies: 

```typescript
 FAIL  tests/unit/__tests__/components/Storyshots.test.js (44.256 s)
  ● Image snapshots › Text Component First Page › Cards Component

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:6006/iframe.html?id=text-component-first-page--cards-component", waiting until "load"
    ============================================================

      at node_modules/@storybook/addon-storyshots-puppeteer/dist/ts3.9/puppeteerTest.js:38:24
      at fulfilled (node_modules/@storybook/addon-storyshots-puppeteer/dist/ts3.9/puppeteerTest.js:5:58)

```

As I mentioned, and you could see here above, this behavior occurs randomly in different components, therefore it is pretty hard to debug or reproduce. 
Here I had two runs, in the first I had `BannerComponent` failed, and in the second `Cards Component`.

```yml
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 17.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 84.0
    Safari: 15.5
  npmPackages:
    @storybook/addon-a11y: ^6.5.7 => 6.5.9 
    @storybook/addon-actions: ^6.5.7 => 6.5.9 
    @storybook/addon-console: ^1.2.3 => 1.2.3 
    @storybook/addon-essentials: ^6.5.7 => 6.5.9 
    @storybook/addon-interactions: ^6.5.7 => 6.5.9 
    @storybook/addon-links: ^6.5.7 => 6.5.9 
    @storybook/addon-storyshots: ^6.5.7 => 6.5.9 
    @storybook/addon-storyshots-puppeteer: ^6.5.7 => 6.5.9 
    @storybook/addon-viewport: ^6.5.7 => 6.5.9 
    @storybook/builder-webpack5: ^6.5.7 => 6.5.9 
    @storybook/manager-webpack5: ^6.5.7 => 6.5.9 
    @storybook/react: ^6.5.7 => 6.5.9 
    @storybook/testing-react: ^1.3.0 => 1.3.0 

```

Does anyone know what could be the reason for such behavior? 

Thanks in advance!
