### ISSUE TITLE
[Bug]: [@storybook/nextjs] Using @next/font breaks storybook v7

### ISSUE THREAD

**Issue by madeleineostoja** [storybookjs/storybook#19711]
### Describe the bug

Using Next 13's new `@next/font` font loader, which is required for loading fonts in the new `/app` routes directory, breaks storybook v7 if it is referenced. Not sure if something can be done to shim it here or if it needs to be fixed upstream.

The workaround is to ensure that no code that touches storybook references the font loader (eg: global styles etc), which could be documented if nothing else.

### System

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 103.0.2
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: future => 7.0.0-alpha.34 
    @storybook/nextjs: ^7.0.0-alpha.41 => 7.0.0-alpha.41
```

### Additional context

![Screenshot 2022-11-02 at 4 54 19 PM](https://user-images.githubusercontent.com/6374876/199392281-d7eafb77-de04-4dda-adec-bc9349e7b588.png)

**Comment by yannbf** [comment]
Hey @madeleineostoja thanks for opening this issue. This is definitely something we want to get working, but it's really tricky, given how the `@next/font` component works. I could be wrong, but I think it:
- Requests the font assets that you need at build time (as you run next dev)
- Stores them as media in the .next folder
- Creates a global css which gets injected somehow
- Provides you a classname which will work as both the assets and css are available

So this process is very Next.js dependent, and it's probably tough to detach. I don't think it's simple to mock it. This exact error happens when running components that use the font import in Jest/Vitest, by the way.

@hanneslund sorry to ping you but I think you're probably the best person to give opinions on how to proceed with this issue. Any thoughts? Would be super nice to be able to use/mock this somehow in external environments. Thank you so much!

**Comment by hanneslund** [comment]
Hi! Is there an example somewhere I can clone and take a look? Thanks!

> which is required for loading fonts in the new /app routes directory

Just to clarify, it's not required but it gives you a bunch of stuff automatically. You can still add `@font-faces` in your CSS as usual.

**Comment by yannbf** [comment]
> Hi! Is there an example somewhere I can clone and take a look? Thanks!

Thanks for the swift reply @hanneslund! I set up an example with instructions here for you:
https://github.com/yannbf/nextjs-font-issue

Happy to discuss further between our teams and come up with a good solution together!

**Comment by robcaldecott** [comment]
I am hitting this issue (using `@next/font/local`) and I can't even mock it out with a webpack alias which is odd. If I could get that to work then I could just import the font as CSS in `preview.js` so my Stories look OK.

main.js
```js
webpackFinal: (config) => {
  // Does not seem to work
  config.resolve.alias["@next/font/local"] = require.resolve("./my-font-mock.js");
  return config;
})
```

my-font-mock.js
```js
function localFont() {
  // This is never called
  return { style: { fontFamily: "Arial" } };
}

export default localFont;
```

preview.js
```js
import { theme } from "../src/theme";
```

theme.js
```js
import localFont from "@next/font/local";
import { createTheme } from "@mui/material";

cont myFont = localFont({ src: "../public/font.woff2" });

return createTheme({
  typography: {
      fontFamily: myFont.style.fontFamily,
    },
});
```

**Comment by hanneslund** [comment]
`@next/font` is now mocked in `next/jest`.

I also got this to work to mock `@next/font/google` in a story.
```js
  webpackFinal: async (config) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      "@next/font/google": require.resolve("./nextFontGoogle"),
    }

    return config;
}
```

This will set the class in `.className` to be named the same as the function imported from `@next/font/google`, e.g. `Playfair_Display`.
```js
// nextFontGoogle.js
module.exports = new Proxy(
    {},
    {
      get: function getter(_, receiver) {
        return () => ({
          className: receiver,
        })
      },
    }
  )
  
```

And then import a CSS files that defines the font inside the story.
```css
@font-face {
  font-family: "Playfair_Display";
  font-style: normal;
  font-weight: 400 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/playfairdisplay/v30/nuFiD-vYSZviVYUb_rj3ij__anPXDTzYgEM86xQ.woff2)
    format("woff2");
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,
    U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215,
    U+FEFF, U+FFFD;
}

.Playfair_Display {
  font-family: "Playfair_Display", serif;
}

```
