### ISSUE TITLE
[Bug]: 'target' is a required option

### ISSUE THREAD

**Issue by NatoBoram** [storybookjs/storybook#19992]
### Describe the bug

Using decorators as described in https://storybook.js.org/docs/svelte/writing-stories/decorators crashes Storybook.

I am unsure if this is because of Storybook, Svelte, TypeScript, Vite or something else.

### To Reproduce

```shell
pnpm create svelte@latest target-required-bug
# ✔ Which Svelte app template? › Skeleton project
# ✔ Add type checking with TypeScript? › Yes, using TypeScript syntax
# ✔ Add ESLint for code linting? … Yes
# ✔ Add Prettier for code formatting? … Yes
# ✔ Add Playwright for browser testing? … Yes
# ✔ Add Vitest for unit testing? … Yes

cd target-required-bug
pnpm i
pnpx storybook@next init
pnpm i --shamefully-hoist
```

#### `src/lib/MarginDecorator.svelte`

```svelte
<div>
  <slot/>
</div>

<style>
  div {
    margin: 3em;
  }
</style>
```

#### `src/lib/YourComponent.svelte`

```svelte
<div />

<style>
  div {
    width: 8em;
    height: 4em;
    background-color: grey;
  }
</style>
```

#### `src/lib/YourComponent.stories.ts`

```typescript
import type { Meta, StoryFn, StrictArgs } from "@storybook/svelte"
import MarginDecorator from "./MarginDecorator.svelte"
import YourComponent from "./YourComponent.svelte"

export default {
  /* 👇 The title prop is optional.
   * See https://storybook.js.org/docs/svelte/configure/overview#configure-story-loading
   * to learn how to generate automatic titles
   */
  title: "YourComponent",
  component: YourComponent,
  decorators: [() => MarginDecorator],
} as Meta<YourComponent>

// Your templates and stories here.
// Don't forget to use the component you're testing and not the MarginDecorator component

const Template: StoryFn<YourComponent> = (args: StrictArgs) => ({
  Component: YourComponent,
  props: args,
})

export const Default = Template.bind({})
```

### System

```yaml
Environment Info:

  System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 9.1.2 - ~/.local/share/pnpm/npm
  Browsers:
    Firefox: 107.0
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/addon-interactions: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/addon-links: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/svelte: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/svelte-vite: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

![image](https://user-images.githubusercontent.com/10495562/204383226-e898863c-de90-491a-aafa-621aeea447fc.png)
