### ISSUE TITLE
[Bug]: Failed to fetch dynamically imported module ( vite storybook 7 )

### ISSUE THREAD

**Issue by himerus** [storybookjs/storybook#20564]
### Describe the bug

Referencing discussion #20472 

From @jongeir:

> Good day.
> I have been testing out storybook 7 with vite for our latest project and since we use GitHub pages it will need to run there also.
>
> For some reason, I cannot make storybook 7 with vite run correctly. It works locally but as soon as it is deployed onto the server, everything inside the storybook iframe will not render.
>
> Here is a screenshot from the GitHub pages. This is a new storybook project using storybook 7.0.0-beta.19
Nothing fancy has been added to the project.

### To Reproduce

```shell
This can also be seen in our current version of Outline when trying to publish to GH Pages at https://outline.phase2tech.com/. 

* https://github.com/phase2/outline/actions/runs/3885467145/jobs/6629776869
* https://github.com/phase2/outline/actions/runs/3885660819
```

### Additional context

In my circumstances, the SAME build command/output works perfectly at Netlify and Chromatic:
* https://outlinejs.style/ 
* https://636082675ab89919e6bcfd40-oxjvhbijks.chromatic.com/

**Comment by tannineo** [comment]
Hi @himerus,

TLDR:

1. add a file called `.nojekyll` to the static folder produced by `storybook build`
2. push the static folder to Github Pages, be careful to push all the files including **dotfiles**

The reason of the error is that some of the `js` filenames start with underscore `_`,
by default Github Pages won't host these files, even they present under the Github Page branch.
We need to add a file called '.nojekyll' at root of the static folder, see this:

https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

This is my `package.json` scripts section, using `gh-pages`. as the example:

```jsonc
{
  // ...
  "scripts": {
    // ...
    "storybook:build": "storybook build",
    "storybook:publish": "pnpm storybook:build && touch ./storybook-static/.nojekyll && gh-pages -d ./storybook-static -t true"
  }
  // ...
}
```

Be careful about the `-t` flag, `gh-pages` by default does not push the dotfiles, and it does not have ONLINE docs for its CLI, but if you type `npx gh-pages -h` you will see the all the files.

**Comment by himerus** [comment]
Thanks @tannineo, this is great info, and mirrors some of what I seemed to find via my searches. I use [crazy-max/ghaction-github-pages](https://github.com/crazy-max/ghaction-github-pages) as part of GitHub Actions to deploy to Pages, vs using the `gh-pages` CLI tool. 

The following configuration of my [build.yml](https://github.com/phase2/outline/blob/next/.github/workflows/build.yml#L218-L229) solved the issue by adding `jekyll: false`. Nothing else needed to change. Turns out they already had the simple config to disable jekyll in place. ¯\_(ツ)_/¯ 

```yaml
- name: Deploy to GitHub Pages
    if: success()
    uses: crazy-max/ghaction-github-pages@v3
    with:
      target_branch: gh-pages
      build_dir: storybook-static
      commit_message: 'chore(deploy): Storybook'
      keep_history: false
      jekyll: false
      fqdn: outline.phase2tech.com
    env:
      GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGES }}
```

Hope these two solutions can help anyone having issues with Storybook 7 and GitHub pages deployments!
