### ISSUE TITLE
[Bug]: Storybook docs CSS cascading into our components

### ISSUE THREAD

**Issue by viveleroi** [storybookjs/storybook#20600]
### Describe the bug

Any "inherited" CSS defined in the storybook docs page leaks into our components. In my case, `font`. I was asked to file a bug here via discord, in order to gather suggested solutions/alternatives.

As of storybook 7 beta 20, the storybook emotion style blocks define:

```css
.css-1j5dgab {
  font-family: "Nunito Sans",-apple-system,".SFNSText-Regular","San Francisco",BlinkMacSystemFont,"Segoe UI","Helvetica Neue",Helvetica,Arial,sans-serif;
}
```

Which applies to the element `<div class="sbdocs sbdocs-content css-1j5dgab">`

The problem is that many of our components styles inherit a global font. We declare `font: 400 10px/1 verdana, sans-serif` in our primary applications css file. Even though that file gets imported into storybook, the storybook CSS overrides it.

This means that our components *actually* have the storybook font styles applied. 

For now, I redeclare our font in every component's CSS file.

Given this is how CSS was designed to work, I only see a few options:

1. Limit selectors to inner SB elements so they can't leak into non-SB elements
2. Use an iframe or some context to wrap components so they don't inherit at all from SB
3. Maybe I can override the SB style via a theme?

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Binaries:
    Node: 18.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.76)
  npmPackages:
    @storybook/addon-docs: 7.0.0-beta.20 => 7.0.0-beta.20
    @storybook/addon-essentials: 7.0.0-beta.20 => 7.0.0-beta.20
    @storybook/addon-interactions: 7.0.0-beta.20 => 7.0.0-beta.20
    @storybook/addon-links: 7.0.0-beta.20 => 7.0.0-beta.20
    @storybook/react: 7.0.0-beta.20 => 7.0.0-beta.20
    @storybook/react-vite: 7.0.0-beta.20 => 7.0.0-beta.20
    @storybook/testing-library: 0.0.14-next.1 => 0.0.14-next.1
```

**Comment by viveleroi** [comment]
Looks like a similar issues was addressed for MDX files here: #19958

**Comment by jtiala** [comment]
We are struggling with the same bug. Our app's global font works well in stories that utilize iframes, but not in docspage where the components are inline with Storybook UI elements.

As a (hopefully) temporary fix, I added css targeting `.docs-story` that tries to reset relevant styles to what our global styles use. Even the css variables from global styles work nicely.

preview.css:
```css
.docs-story {
  background-color: var(--color-white);
  font-family: var(--font-family-sans);
  font-size: var(--font-size-sm);
  font-weight: var(--font-weight-regular);
  -webkit-font-smoothing: var(--font-smoothing-webkit);
  -moz-osx-font-smoothing: var(--font-smoothing-moz);  
  color: var(--color-gray-90);
}
```

preview.js:
```js
import "../src/styles/index.css"; // our global styles
import "./preview.css";

...
```
