### ISSUE TITLE
Update references regarding storybook-deployer and github-pages

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22710]
Given that storybook-deployer is unmaintained, we should take a look at ways to update documentation regarding Storybook and GH pages. Here's a good idea from discussions:

using the github-pages-deploy-action GitHub Action:

1. Create a new GitHub Actions workflow in your repository by creating a .github/workflows/deploy.yml file with the following contents:

```
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and deploy Storybook
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./storybook-static
```

* Note: Replace ./storybook-static with the path to your built Storybook directory.

2. In your CI pipeline, build your Storybook as you normally would.
3. Push your changes to the main branch of your repository, which will trigger the GitHub Actions workflow to deploy your Storybook to GitHub Pages.

With this approach, you don't have to worry about setting up any additional tools or dependencies, as GitHub Action takes care of the deployment for you.

_Originally posted by @AmiramAbergel in https://github.com/storybookjs/storybook/discussions/20932#discussioncomment-4935598_
