### ISSUE TITLE
[Bug]: Deploying to Github Pages is creating `assets/assets`path

### ISSUE THREAD

**Issue by Tragio** [storybookjs/storybook#26854]
### Describe the bug

Hi team 👋 

I'm using Storybook 8 and deploying it to the GitHub Pages. The Storybook works but then it is doubling the `assets/assets` path instead of being just one `assets/`. All the files are correctly there, but for some reason, it is doubling the path 🤔 

![CleanShot 2024-04-16 at 10 49 19@2x](https://github.com/storybookjs/storybook/assets/5109593/fe25a424-f742-4ba8-8017-204648c7ef59)

Thank you for the amazing work!!

### To Reproduce

main.ts
```js
import { join, dirname } from 'path';

/**
 * This function is used to resolve the absolute path of a package.
 * It is needed in projects that use Yarn PnP or are set up within a monorepo.
 */
function getAbsolutePath(value) {
  return dirname(require.resolve(join(value, 'package.json')));
}

/** @type { import('@storybook/vue3-vite').StorybookConfig } */
const config = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    getAbsolutePath('@storybook/addon-links'),
    getAbsolutePath('@storybook/addon-essentials'),
    getAbsolutePath('@chromatic-com/storybook'),
    getAbsolutePath('@storybook/addon-interactions'),
  ],
  staticDirs: ['./public'],
  framework: {
    name: getAbsolutePath('@storybook/vue3-vite'),
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
};
export default config;
```

action.yml:
```yml
name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: npm run build-storybook
        working-directory: packages/demo-components

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: packages/demo-components/storybook-static
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.10.0/bin/npm <----- active
    pnpm: 8.6.2 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Safari: 17.4.1
```
