### ISSUE TITLE
[Bug]: `storybook init` fails to setup dependencies correctly when `--skip-install` install is set in ci/cd pipeline

### ISSUE THREAD

**Issue by manuel3108** [storybookjs/storybook#27096]
### Describe the bug

This is the `package.json` that was produced by the storybook cli:

```jsonc
{
  "name": "storybook-missing-packages-repro",
  // ...
  "scripts": {
    // ...
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^3.0.2",
    "svelte": "^4.2.12",
    "vite": "^5.2.0",
    "@chromatic-com/storybook": "^1.3.5"
  }
}
```

The initializer only added `@chromatic-com/storybook` for whatever reason, and skips adding all other packages, although the cli output says `Getting the correct version of 9 packages`. Therefore I would expect to see 9 additional packages in my `package.json`

Only happens if `--skip-install` is set. Otherwise everything works correctly.

### To Reproduce

Here is a simple github workflow to try it out: https://github.com/manuel3108/storybook-missing-packages-repro/blob/test-2/.github/workflows/pr.yml
```yml
name: Pull requests
# ...
jobs:
    test:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
           # ...

            - name: cat package.json
              run: cat package.json

            - name: add storybook
              run: npx storybook init --skip-install

            - name: cat package.json
              run: cat package.json

```

You can find the latest workflow output here: https://github.com/manuel3108/storybook-missing-packages-repro/actions/runs/9045619764/job/24855552856

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.12.2 - /opt/hostedtoolcache/node/20.12.2/x64/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.0 - /opt/hostedtoolcache/node/20.12.2/x64/bin/npm <----- active
    pnpm: 9.1.0 - /opt/hostedtoolcache/node/20.12.2/x64/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.60
```

```[tasklist]
### Tasks
```
