### ISSUE TITLE
[Bug]: Weird CSS added that affects docs styling

### ISSUE THREAD

**Issue by jakubmazanec** [storybookjs/storybook#28866]
### Describe the bug

In my Storybook, there is following CSS added to some iframes that shows a docs page:

```css
.css-qa4clq :where(div:not(.sb-anchor, .sb-unstyled, .sb-unstyled div)) {
  font-family:
    "Nunito Sans",
    -apple-system,
    ".SFNSText-Regular",
    "San Francisco",
    BlinkMacSystemFont,
    "Segoe UI",
    "Helvetica Neue",
    Helvetica,
    Arial,
    sans-serif;
  font-size: 16px;
  margin: 0;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  -webkit-overflow-scrolling: touch;
}

```

The selector has high specificity, so it makes styling divs more difficult, and also the font styles are inherited, so I have to needlessly add classes to override that - but those classes won't be needed when I use the components elsewhere.

### Reproduction link

https://666f2dc8033dde8c47f6a278-exnfuvkrwz.chromatic.com/?path=/docs/forms--docs

### Reproduction steps

1. Open the reproduction link.
2. On Forms page, inspect label "Name"
3. See that I have to needlessly specify font-family (via `font-sans` Tailwind class), because otherwise styling is inherited from the weird CSS described above.

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5825U with Radeon Graphics
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (127.0.2651.74)
```
