### ISSUE TITLE
[Bug]: Build Fails on GitHub Actions: `import_common.handlebars` Error

### ISSUE THREAD

**Issue by saadamir-2** [storybookjs/storybook#29746]
### Describe the bug

The build for our Storybook project is failing on GitHub Actions while running successfully in the local environment. Two days ago, the same GitHub Action passed successfully for this pull request, but it started failing yesterday without any changes to the configuration.

The issue occurs when executing the following command:
npm run build-storybook -- --stats-json

Error Message:
=> Failed to build the preview  
 NX   (0 , import_common.handlebars) is not a function  

Troubleshooting Steps Taken:

1. Verified that the same command runs successfully on local machines.
2. Cleared the cache and reinstalled dependencies in the local environment, but the issue persists only on GitHub Actions.
3. Confirmed no changes were made to the GitHub Action workflow or build scripts recently.

### Reproduction link

na

### Reproduction steps

I am unable to attach the .yml file so I have provided the code of our github action .yml file below.

```
# .github/workflows/storybook.yml

name: 'Chromatic Tests'

on:
  workflow_dispatch:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
    types: [opened, edited, synchronize]

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.16.0
      - name: Install dependencies
        # See your package manager's documentation for the correct command to install dependencies in a CI environment.
        run: npm i
      - name: Build Storybook with stats
        run: npm run build-storybook -- --stats-json
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: 'xyz'

```

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (128.0.2739.79)
  npmPackages:
    @storybook/addon-essentials: 8.2.0 => 8.2.0 
    @storybook/core-common: 8.2.0 => 8.2.0 
    @storybook/core-server: 8.2.0 => 8.2.0 
    @storybook/react: 8.2.0 => 8.2.0 
    @storybook/react-webpack5: ^8.2.0 => 8.3.3 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
```
