### ISSUE TITLE
Escaped pseudo-states in class selectors produce invalid rules

### ISSUE THREAD

**Issue by sentience** [storybookjs/storybook#31409]
For a Storybook with this rule in its stylesheet:

```css
@layer utilities {
  @media (hover: hover) {
    body .prc\:hover\:cursor-default:hover {
      cursor: default;
    }
  }
}
```

…I am getting this console error from the pseudo-states add-on:

> SyntaxError: Failed to execute 'insertRule' on 'CSSGroupingRule': the rule 'body .prc\\:hover\\:cursor-default:hover, body .prc\\.pseudo-hover\\:cursor-default.pseudo-hover, .pseudo-hover-all body .prc\\\\:cursor-default { cursor: default; }' is invalid and cannot be parsed.

Looks like perhaps there's an issue with the escaped colons (`\:`) in the selector, which are producing a double backslash in the injected CSS?
