### ISSUE TITLE
Nested media query breaks hover-state detection/transformation

### ISSUE THREAD

**Issue by hpohlmeyer** [storybookjs/storybook#31410]
Tailwind v4 creates hover selectors, that look like this:

```html
<p class="hover:text-red-500">Test</p>
```

will generate this css:

```css
@layer utilities {
  .hover\:text-red-500 {
    &:hover {
      @media (hover: hover) {
        color: var(--color-red-500);
      }
    }
  }
}
```

I would expect this to be transformed to

```css
@layer utilities {
  .hover\:text-red-500 {
    &:hover, &.pseudo-hover, .pseudo-hover-all & {
      @media (hover: hover) {
        color: var(--color-red-500);
      }
    }
  }
}
```

but that does not seem to be happening. I’ve tracked it down to the nested media query, that seems to throw `storybook-addon-pseudo-states` off. Removing it works:

```css
@layer utilities {
  .hover\:text-red-500 {
    &:hover {
      color: var(--color-red-500);
    }
  }
}
```

will be transformed to

```css
@layer utilities {
  .hover\:text-red-500 {
    &:hover, &.pseudo-hover, .pseudo-hover-all & {
      color: var(--color-red-500);
    }
  }
}
```

**Comment by hpohlmeyer** [comment]
Hey @vanessayuenn, since you’ve added the "help wanted" tag. I’ve opened https://github.com/storybookjs/storybook-addon-pseudo-states/pull/139 to fix the problem. Can you transfer the PR as well, or do I need to recreate it here?

**Comment by vanessayuenn** [comment]
Unfortunately I can't transfer the PRs over repos like that since the addon has been [migrated](https://github.com/storybookjs/storybook/tree/next/code/addons/pseudo-states) over to this monorepo. But if you're able to open the same PR here again, we'd be delighted to review it. Thanks!

**Comment by hpohlmeyer** [comment]
Sorry, it took a while, but the new PR is here now. (#33605)

**Comment by Lukas-Kullmann** [comment]
For what it's worth, this also affects Tailwind 4's style of providing color transparency (see https://tailwindcss.com/docs/colors#adjusting-opacity)

For example, `focus-visible:ring-ring/50` results in

```css
.focus-visible\:ring-ring\/50 {
    &:focus-visible {
        @supports (color: color-mix(in lab, red, red)) {
            --tw-ring-color: color-mix(in oklab, var(--ring) 50%, transparent);
        }
    }
}
```

Which currently does not work as well. I think however that @hpohlmeyer's PR also covers this issue. (By the way, the build on your PR is failing)
