### ISSUE TITLE
Addon-docs: User #root styles breaks Docs tab

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7840]
### Problem

User applied the following global style to the preview iframe:

```css
#root {
  height: 100vh;
  display: flex;
  flex-direction: column;
}
```

This breaks docs in the following way. When the user click on the `Docs` tab, Storybook applies the `hidden` attribute to `#root`, which triggers the following browser CSS:

```css
[hidden] {
  display: none;
}
```

However, the `#root` CSS is more specific, so the Story renders on top of the docs.

### Solution

When we added the following CSS to the user's code, it fixed it.

```css
#root[hidden] {
  display: none;
}
```

We can add this to Storybook itself to avoid this issue for users that style `#root` (which is a completely reasonable thing to do).

However, I'm not sure this is enough...
