### ISSUE TITLE
Hot reloading inside docker containers

### ISSUE THREAD

**Issue by jdelucaa** [storybookjs/storybook#8147]
**Describe the bug**

I use @storybook/react.

I have all my dev environment in docker containers (my react apps) and my storybook. I use `docker-compose up` to run all of them. The only one that's having issues with hot reloading is the storybook one. 
Hot reloading works fine running storybook outside the container.

**To Reproduce**
- Create a react-app with CRA.
- Install and configure storybook/react

Here's my dockerfile:

```FROM library/node:12.7-stretch-slim as build

ARG PATH_TO_SRC=./src/packages/my-storybook-app

WORKDIR /app

COPY .prettierrc.yaml .
COPY .editorconfig .
COPY ${PATH_TO_SRC}/package.json .
COPY ${PATH_TO_SRC}/package-lock.json .

RUN npm set progress=false && npm config set depth 0

RUN npm ci

COPY ${PATH_TO_SRC} .

RUN npm run format:check

RUN npm run storybook:build

#
# ---- Test ----
FROM build as test

ENV CI=true

RUN npm run test

#
# ---- Release ----
FROM nginx:1.17-alpine

COPY --from=build /app/storybook-dist /usr/share/nginx/html
```

The npm command `storybook:build` seen above is the following:
`"storybook:build": "build-storybook -s public -o storybook-dist",`

Here's my `docker-compose` file:

```
version: "3.7"

services:
  storybook:
    build:
      context: .
      dockerfile: build/storybook.Dockerfile
      target: build
    command: "npm run storybook"
    ports:
      - "9003:9003"
    volumes:
      - ./src/packages/my-storybook-app:/app
      - /app/node_modules/
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
```

The npm command `npm run storybook` seen above is the following:
`"storybook": "start-storybook -p 9003"`

Am I missing something? Any ideas?

**Expected behavior**
Hot reload should work when running storybook in a docker container just like other regular react apps.

**System:**
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    @storybook/addon-actions: ^5.2.1 => 5.2.1
    @storybook/addon-links: ^5.2.1 => 5.2.1
    @storybook/addons: ^5.2.1 => 5.2.1
    @storybook/react: ^5.2.1 => 5.2.1

**Additional context**
I added `module` to my stories.
